fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            .*.terraform/.*|
            tmpl\/.*.sops\.ya?ml
            )$
      - id: mixed-line-ending
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  #- repo: https://github.com/hhatto/autopep8
  #  rev: v2.3.1
  #  hooks:
  #    - id: autopep8
  #      args:
  #        - --aggressive
  #        - --aggressive
  #        - --aggressive
  #        - --in-place
  #        - --list-fixes
  #        - --max-line-length=79
  #        - --pep8-passes=5

  # YAPF configuration is in pyproject.toml
  #- repo: https://github.com/google/yapf
  #  rev: v0.40.2
  #  hooks:
  #  - id: yapf
  #    args: ['--in-place', '--verbose', '--style', 'google']

  # Black configuration is in pyproject.toml
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: ['--config=pyproject.toml']

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ['--config=pyproject.toml']
        #additional_dependencies: [
        #  dlint,                      # Tool for encouraging best coding practices and helping ensure Python code is secure.
        #  flake8-alphabetize,         # Checking the order of import statements and the __all__ list.
        #]



###
###     - repo: https://github.com/pre-commit/mirrors-mypy
###       rev: v1.10.1  # Use the latest stable release
###       hooks:
###         - id: mypy
###
###     - repo: https://github.com/PyCQA/isort
###       rev: 5.13.2  # Use the latest stable release
###       hooks:
###         - id: isort
###           name: isort (python)  # Optional, customize hook name
###           args: ['--profile', 'black']  # Example of passing arguments to isort
###           language_version: python3  # Specify the Python version
###
###     - repo: https://github.com/pylint-dev/pylint
###       rev: v3.2.5  # Use the latest stable release
###       hooks:
###         - id: pylint
###           args: ['--disable=R,C']  # Example of disabling specific pylint categories

  #- repo: https://github.com/djh00t/sops-pre-commit
  #  rev: v0.0.2f
  #  hooks:
  #    - id: kubernetes-secret
  #      exclude: (tmpl\/.*.sops\.ya?ml|knative\-operator\.ya?ml)
  #    - id: aws-access-key-id
  #    - id: aws-secret-access-key
  #    - id: rsa-private-key
  #    - id: ssh-private-key
  #    - id: github-access-token
  #    - id: generic-api-key
  #    - id: gcp-api-key
  #    - id: jwt
  #    - id: slack-webhook-url
  #    - id: google-oauth-client-secret

  - repo: local
    hooks:
      - id: aws-access-key-id
        name: Check for AWS Access Key IDs
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id aws-access-key-id
        language: system
        files: ((^|/)*.(ya?ml)$)
        exclude: tests/.*\.ya?ml$

      - id: aws-secret-access-key
        name: Check for AWS Secret Access Keys
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id aws-secret-access-key
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: gcp-api-key
        name: Check for GCP API Keys
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id gcp-api-key
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: generic-api-key
        name: Check for Generic API Keys
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id generic-api-key
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: github-access-token
        name: Check for GitHub Access Tokens
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id github-access-token
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: google-oauth-client-secret
        name: Check for Google OAuth Client Secrets
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id google-oauth-client-secret
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: jwt
        name: Check for JSON Web Tokens (JWT)
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id jwt
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: rsa-private-key
        name: Check for RSA Private Keys
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id rsa-private-key
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: slack-webhook-url
        name: Check for Slack Webhook URLs
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id slack-webhook-url
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: ssh-private-key
        name: Check for SSH Private Keys
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id ssh-private-key
        language: system
        files: ((^|/)*.(ya?ml)$)

      - id: kubernetes-secret
        name: Check for unencrypted Kubernetes secrets
        entry: python ../sops-pre-commit/hooks/forbid_secrets.py --hook-id kubernetes-secret
        language: system
        files: ((^|/)*.(ya?ml)$)
        exclude: tests/.*\.ya?ml$

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
