name: Auto PR

on:
  push:
    branches-ignore:
      - main
      - master
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global init.defaultBranch main

      - name: Generate PR title and body using GitHub Copilot
        id: copilot_pr
        run: |
          echo "title=$(copilot-pr-title)" >> $GITHUB_ENV
          echo "body=$(copilot-pr-body)" >> $GITHUB_ENV

      - name: Create or update PR
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update PR'
          branch: ${{ github.ref }}
          title: ${{ env.title }}
          body: ${{ env.body }}
          draft: false

  update-release-notes:
    runs-on: ubuntu-latest
    needs: create-pr
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release notes
        id: release_notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/workflows/release_configuration_complex.json
          token: ${{ secrets.GITHUB_TOKEN }}

  run-tests:
    needs: [create-pr, update-release-notes]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

