#!/bin/bash
###
### push redirector
###

echo "This script has been deprecated. It is replaced by the klingon_tools
pip package. To install it run `pip install klingon_tools` once it is
installed you will have a `push` command added to your python environment.
For more information see the REEADME.md at
https://github.com/djh00t/klingon_tools"

exit 0
