name: 🚀 Deploy to TestPyPI and PyPI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install test dependencies
        run: |
          pip install pytest

      - name: Increment version
        id: version
        run: |
          export VERSION=$(cat VERSION)
          export NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          PYPI_VERSION=$(curl -s https://pypi.org/pypi/klingon_tools/json | jq -r .info.version)
          TEST_PYPI_VERSION=$(curl -s https://test.pypi.org/pypi/klingon_tools/json | jq -r .info.version)
          HIGHEST_VERSION=$(echo -e "$NEW_VERSION\n$PYPI_VERSION\n$TEST_PYPI_VERSION" | sort -V | tail -n 1)
          if [ "$HIGHEST_VERSION" != "$NEW_VERSION" ]; then
            NEW_VERSION=$(echo $HIGHEST_VERSION | awk -F. '{print $1"."$2"."$3+1}')
          fi
          echo $NEW_VERSION > VERSION
          sed -i "s/version=\"[0-9]*\.[0-9]*\.[0-9]*\"/version=\"$NEW_VERSION\"/" setup.py
          git add VERSION setup.py
          git commit -m "Bump version to $NEW_VERSION"
          git push origin main
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Create and Merge Version Update PR
        uses: peter-evans/create-pull-request@v6
        id: create_pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          merge-commit-message: "chore: bump version to ${{ steps.version.outputs.new_version }}"
          merge-commit-title: "Version bump to ${{ steps.version.outputs.new_version }}"
          merge-commit-body: "This PR was automatically created by GitHub Actions."
          commit-message: 'chore: bump version to ${{ steps.version.outputs.new_version }}'
          branch: update-version-${{ steps.version.outputs.new_version }}
          title: "chore: bump version to ${{ steps.version.outputs.new_version }}"
          body: "This PR bumps the version to ${{ steps.version.outputs.new_version }}."


      - name: Build and Test
        run: |
          python setup.py sdist bdist_wheel
          pip install .
          make test

      - name: Deploy to TestPyPI
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u ${{ secrets.TEST_PYPI_USER_AGENT }}

      - name: Test from TestPyPI
        run: |
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple my-package

      - name: Deploy to PyPI
        run: |
          twine upload dist/* -u ${{ secrets.PYPI_USER_AGENT }}
