name: 📦 Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release notes
        id: release_notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
