name: "🚨 Run Tests"

on:
  #pull_request:
  #  branches:
  #    - '**'
  workflow_run:
    workflows: ["Auto PR"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run make check-packages
        run: make check-packages

      - name: Install klingon_tools
        run: make install

      - name: Run tests
        run: make test
