name: "\U0001F6A8 Run Tests"
true:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - ready_for_review
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.x
    - name: Cache pip
      uses: actions/cache@v4.0.2
      with:
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        path: ~/.cache/pip
        restore-keys: '${{ runner.os }}-pip-

          '
    - name: Run make check-packages
      run: make check-packages
    - name: Install klingon_tools
      run: make install
    - name: Run tests
      run: make test
